name: RL Tournament Validation Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Agent and Submit
    runs-on: [ubuntu-latest] 
    container:
      image: python:3.10-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install dependencies
        run: |
          chmod +x install.sh
          ./install.sh

      - name: Run validation
        run: |
          python validate.py
