name: RL Tournament Battle Pipeline

on:
  workflow_dispatch:
    inputs:
      branch1:
        description: 'First Agent (cannot be main)'
        required: true
      branch2:
        description: 'Second Agent (cannot be main)'
        required: true

jobs:
  check-inputs:
    name: Validate Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Validate branches
        run: |
          if [ "${{ github.event.inputs.branch1 }}" = "main" ] || [ "${{ github.event.inputs.branch2 }}" = "main" ]; then
            echo "Error: Cannot use 'main' branch."
            exit 1
          fi
          if [ "${{ github.event.inputs.branch1 }}" = "${{ github.event.inputs.branch2 }}" ]; then
            echo "Error: Branches must be different."
            exit 1
          fi

  check-submissions:
    name: Check Submission Pipeline Status
    runs-on: ubuntu-latest
    needs: check-inputs
    steps:
      - name: Check branch1 submission
        run: |
          STATUS=$(gh run list --branch "${{ github.event.inputs.branch1 }}" --workflow "RL Tournament Pipeline" --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "Error: Latest submission pipeline for branch1 failed or not found."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check branch2 submission
        run: |
          STATUS=$(gh run list --branch "${{ github.event.inputs.branch2 }}" --workflow "RL Tournament Pipeline" --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "Error: Latest submission pipeline for branch2 failed or not found."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  battle:
    name: Battle
    runs-on: ubuntu-latest
    needs: check-submissions
    container:
      image: python:3.10-slim
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run battle
        run: |
          python battle.py "${{ github.event.inputs.branch1 }}" "${{ github.event.inputs.branch2 }}"
