name: RL Tournament Battle Pipeline

on:
  workflow_dispatch:
    inputs:
      username1:
        description: 'GitHub username of first participant (fork owner)'
        required: true
      username2:
        description: 'GitHub username of second participant (fork owner)'
        required: true

jobs:
  check-inputs:
    name: Validate Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Validate usernames
        run: |
          if [ "${{ github.event.inputs.username1 }}" = "${{ github.event.inputs.username2 }}" ]; then
            echo "Error: Usernames must be different."
          fi

  battle:
    name: Battle
    runs-on: ubuntu-latest
    needs: check-inputs
    container:
      image: python:3.10

    steps:
      # Step 1: Checkout the main repo
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          ref: aling/battle

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          chmod +x install.sh
          ./install.sh

      # Step 3: Clone participant forks
      - name: Clone forks
        run: |
          echo "Cloning fork for ${{ github.event.inputs.username1 }}"
          git clone "https://github.com/${{ github.event.inputs.username1 }}/$(basename $GITHUB_REPOSITORY)" fork1

          echo "Cloning fork for ${{ github.event.inputs.username2 }}"
          git clone "https://github.com/${{ github.event.inputs.username2 }}/$(basename $GITHUB_REPOSITORY)" fork2

      # Step 4: Copy each agent to main repo under `agents/`
      - name: Copy agents to main repo
        run: |
          mkdir -p agents/${{ github.event.inputs.username1 }}
          mkdir -p agents/${{ github.event.inputs.username2 }}

          cp fork1/user/my_agent.py agents/${{ github.event.inputs.username1 }}/my_agent.py
          cp fork2/user/my_agent.py agents/${{ github.event.inputs.username2 }}/my_agent.py

          echo "Agents copied successfully:"
          ls -R agents

      # Step 5: Run battle
      - name: Run battle
        run: |
          python3 -m pytest user/battle.py -- --agent1 "agents/${{ github.event.inputs.username1 }}/my_agent.py" --agent2 "agents/${{ github.event.inputs.username2 }}/my_agent.py"
